php-gettext/Gettext

src/Extractors/Extractor.php

When reading an empty file, fread throws this warning:
`Warning: fread(): Length parameter must be greater than 0 in ...Extractors/Extractor.php on line 84`
Let's fix this :wink:

Avoid warning while reading an empty file

---

.travis.yml
phpunit.xml
src/Extractors/Mo.php
src/Generators/Mo.php
tests/MoGenerationTest.php

- Add a phpunit.xml file so that tests can be run with `phpunit` instead of `phpunit tests`
- Fix `Extractors\Mo::fromString` so that it returns the newly created stuff (`Gettext\Translations::fromMoString('...');` always returns null otherwise)
- Add a test to check the generated .mo data.
Please note that this new test **will fail**, denoting that the .mo generation is broken.
I'll update this PR to add some fixes.

Mo genetation stuff

---

src/Generators/Mo.php

Plural forms should not be considered when determining message uniqueness in gettext files.
See https://github.com/oscarotero/Gettext/issues/48

Consider messages as unique if they only have same context+single

---

src/Translation.php
src/Translations.php

gettext/gettext currently can extracts strings from source files, thus creating an dictionary of translations (in GNU-gettext terms it may be seen as a POT - Portable Object Template - file).
When creating translations for other languages, we may need to change the plural count of the translations. So, let's introduce this new `setPluralCount` method.
For instance, here's a whole process to create two translation (.po) files, one for Russian (3 plural rules) and one for Japanese (1 plural rule):
```php
$pot = \Gettext\Translations::fromPhpCodeFile($file);
$ruPo = clone $pot;
$ruPo->setPluralCount(3);
$jaPo = clone $pot;
$jaPo->setPluralCount(1);
```

Add methods to create Translations with different plural rules

---

src/Translations.php

Consistency between phpDoc and actual variable name

Fixing typo

---

src/Utils/Locales.php

Allow getLocaleInfo to be called with a complex locale identifier.
As for the Unicode specs, locale identifiers may be composed by:
- language code (2 to 3 letters)
- script (4 letters)
- territory (2 letters or 3 numbers)
This PR parses the locale code and extract the language code (mandatory), the script (optional) and the territory (optional).
So, it can accept codes like
- `'it'`
- `'it_IT'`
- `'it_Latn'`
- `'it_Latn_IT'`

Allow getLocaleInfo to accept variants

---

.gitattributes

With this change, the archives downloaded from https://github.com/oscarotero/Gettext/releases don't contain development stuff

Remove development stuff from downloadable archives

---

src/Generators/Mo.php

Hi,
I just started using this library in one of my applications and everything worked great until I generated the final mo file. It seems that the way it currently works it will generate empty strings for all non translated strings in the mo file. Skipping the untranslated translations seems to fix this and it appears to be what PoEdit is doing. I compared file sizes when using PoEdit and when generating with the Gettext library and they appear to be about the same now with this fix.

Fix mo file generation

---

composer.json
src/Extractors/Extractor.php
src/Extractors/Twig.php

Note I haven't added tests - not sure how I should handle that given the required libraries are only suggested in composer (means automated testing will fail unless it also pulls down the suggestions).
Happy to add tests if this isn't a problem.

Added Twig extractor support

---

src/Utils/FunctionsScanner.php

The PhpFunctionsScanner extracts empty strings too (eg `echo __('');`). So, we risk to generate a .po file like this:
```po
msgid ""
msgstr ""
"Header 1: value\n"
"Header 2: value\n"
msgid ""
msgstr ""
...
```
This is wrong, since the msgid must be unique (and this specific case messes up the gettext headers).

Avoid adding empty strings

---

tests/JsCodeExtractorTest.php
tests/files/jscode.js

Hi,
I'm using your library into Pharinix to manage translations, but I have problems when extract text from Javascript code. Some times not detect the translation functions, other get a incomplete string.
By this, I changed the JsCodeExtractorTest and the dummy js file to get the same error.
Thanks, I hope will be helpfull.

Added new js usage that break extractor test and asserts that catch it.

---

src/Extractors/PhpCode.php

Use case:
//Scan the php code from a string to find the latest gettext translations
$translations = Translations::fromPhpCodeString($string2translate);
//Get the translations of the code that are stored in a po file
$poTranslations = Translations::fromPoFile('en.po');
//Apply the translations from the po file to the translations, and merges header and comments but not references and without add or remove translations:
$translations->mergeWith($poTranslations, Translations::MERGE_HEADERS | Translations::MERGE_COMMENTS);
//Now save a po file with the result
$translations->toPoFile('en_new.po');

return translations object from PhpCode::fromString

---

src/Utils/PhpFunctionsScanner.php
tests/DecodePhpStringTest.php
tests/PhpCodeExtractorTest.php
tests/files/special-chars.php

Let's consider this source code:
```php
<div>
<p><?php __('plain'); ?></p>
<p><?php __('DATE \a\t TIME'); ?></p>
<p><?php __("DATE \a\\t TIME"); ?></p>
<p><?php __("DATE \\a\\t TIME"); ?></p>
<p><?php __("FIELD\tFIELD"); ?></p>
</div>
```
Here we have only 3 different strings, but the php extractor finds these strings:
```po
msgid "plain"
msgstr ""
msgid "DATE \\a\\t TIME"
msgstr ""
msgid "DATE \\a\\\\t TIME"
msgstr ""
msgid "DATE \\\\a\\\\t TIME"
msgstr ""
msgid "FIELD\\tFIELD"
msgstr ""
```

Add test for some PHP special chars

---

src/Generators/Po.php
tests/MoGenerationTest.php
tests/TranslationsTest.php
tests/files/expected-po.po
tests/files/jed.json
tests/files/po.po

Test multibyte and tab chars

---

.travis.yml

In TravisCI you see this message:
```
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
```
Let's hide it :wink:

Disable composer warning about xdebug:

---

src/Extractors/PhpCode.php

Fix https://travis-ci.org/oscarotero/Gettext/jobs/110222372

Fix extraction of php strings

---

src/Utils/ParsedFunction.php
src/Utils/PhpFunctionsScanner.php
tests/PhpCodeExtractorTest.php
tests/files/special-chars.php

I run a few tests again a PHP project with ~4300 translatable strings, comparing the results of `xgettext` and those of the `PhpCode` extractor.
I only found two problems:
1) `xgettext` (correctly) does not extracts strings like the `me` in `__($avoid['me'])`. I think that the correct solution would be to do not extract strings with variables (since it does not have any sense), but gettext stops as soon as it find a variable (for instance from `__('Stop at the variable'.$var.'!')` it extracts `Stop at the variable`) - so I'd adopt this same approach for consistency.
2) Consider this example:
```php
__(
'line1'
.' line2')
```
xgettext (correctly) extracts `'line1 line2'`, but the `PhpCode` extractor only extracts `'line1'`.
I added some tests here to highlight the above problems.

Extraction of variables and concatenated strings

---

src/Extractors/PhpCode.php
src/Utils/FunctionsScanner.php
src/Utils/ParsedFunction.php
src/Utils/PhpFunctionsScanner.php
tests/PhpCodeExtractorTest.php
tests/files/phpcomments.php

Follow-up of #100: what about a code like this?

Comments extraction from PHP code

---

src/BaseTranslator.php
src/translator_functions.php

This delegates actual translation to `BaseTranslator::$current->npgettext`
I hope this was just an oversight and there isn't a reason to exclude this particular translation function.
Since this is just an alias, I thought testing would not be helpful.

Register np__() along with the other global functions.

---

README.md
src/Extractors/CsvDictionary.php
src/Generators/CsvDictionary.php
tests/CsvDictionaryExtractorTest.php
tests/CsvDictionaryGeneratorTest.php
tests/files/generated.csv

CSV files are a good format for customers and non-developers.
To exchange translations with them a csv generator and extractor have been introduced.

CSV Generator and Extractor

---

src/BaseTranslator.php
src/Extractors/JsCode.php
src/Extractors/PhpCode.php
src/TranslatorInterface.php
src/translator_functions.php
tests/TranslatorTest.php

While PHP's gettext-library lacks `gettext_noop()`, several other languages (and frameworks) has one (C, C++, and GCC, Lisp, Scheme, perl as per https://www.gnu.org/savannah-checkouts/gnu/gettext/manual/html_node/xgettext-Invocation.html). 
`gettext_noop()` marks a string as translatable, in order to make it discoverable by extractors, without actually translating it. It is a workaround for translating the contents of variables: as the variable is set, its contents are also marked with `gettext_noop()`:
```
$message = gettext_noop('This is the message');
echo gettext($message);
```
While some language-dependent variant of "gettext-noop" seems to be in use everywhere that has it, the actual look (or necessity) of `N__` is up for debate.

New feature: Method/function gettext_noop

---

README.md
src/translator_functions.php
tests/TranslatorTest.php

When the last argument is an array, strtr will be used instead of vsprintf for all the functions `__()`, `n__()`, etc.
This allow using named placeholders, e.g.
`__('Hello %name%', ['%name' => 'world'])`
Existing syntax using vsprintf is preserved, e.g.
`__('Hello %s', 'world')`
Fix #138
Notes:
- I explicitly added `$args` to the function declaration to avoid calling `func_num_args()` if not necessary. It is marginally faster.
- I didn't find existing tests for all the `*gettext` methods/functions so I added a bunch.

Adding support for named placeholders in functions

---

src/Utils/JsFunctionsScanner.php

Fixed extracting single quoted messages from JavaScript source codes, as described in issue #140

Fixed JavaScript source extraction with single quoted functions

---

src/Extractors/Csv.php
src/Generators/Csv.php

Make csv options configurable via $options, defaults are set to the PHP defaults.
`Translations::fromCsvFile($destination, ['delimiter' => ';']);`
```
$translations->toCsvFile(
$pathinfo['dirname'] . '/' . $pathinfo['filename'] . '.csv',
[
'includeHeaders' => true,
'delimiter' => ';'
]
);
```

Make csv options configurable via $options

---

src/Merge.php

Fix for https://github.com/oscarotero/Gettext/issues/147: It was not possible to overwrite translations correctly when using `mergeWith`, as in:
```
$translations->mergeWith($otherTranslations, Merge::ADD | MERGE::HEADERS_ADD | MERGE::HEADERS_OVERRIDE | Merge::TRANSLATION_OVERRIDE);
```
Options were not correctly passed on to `Merge::mergeTranslations()`.

Correctly passing on options when merging Translations objects

---

src/Translator.php
tests/TranslatorTest.php

If the translation key is unknown, we use the English plural rules, as it is done in PHP gettext extension
Fixes #148

Unify plural behaviours between PHP gettext and Translator

---

src/Merge.php

Clone translation before merging to avoid unintended modification of referenced `Translation` objects.

Clone translation before merging

---

src/Utils/JsFunctionsScanner.php

add fix to skip ' with trailing slash in translation for example {i18n.__('You don\'t have any bookmark.')}

add fix to skip ' with trailing slash

---

src/Extractors/JsCode.php
src/Extractors/PhpCode.php
src/Utils/FunctionsScanner.php

While extracting translations I noticed the `dn__` function was not working. 
I added it to the applicable extractors and functions scanner switch case.

Add dn__ function to both extractors and functions scanner

---

src/Translator.php
tests/TranslatorTest.php

There wasn't any input validation on eval'd code in plural forms. Untrusted translation files could create php injection.

php injection - validate eval input from plural forms

---

src/Translations.php
src/Translator.php
tests/TranslatorTest.php

My previous PR https://github.com/oscarotero/Gettext/pull/156 missed some characters in plural forms validation

fix plural forms validation

---

src/translator_functions.php

The function description for dn__ seems to have been copy/pasted from dp__ and wasn't reflecting it's actual purpose.

Fixed incorrect function description

---

.gitattributes

There's no need for `CHANGELOG.md`, `CONTRIBUTING.md` and `phpcs.xml` to be part of the package when installing the library via Composer.

Extend .gitattributes file

---

composer.json
phpunit.xml
tests/AbstractTest.php
tests/TranslatorTest.php
tests/bootstrap.php

- Set  the higher PHPUnit version for the ```php-7.2```.
- Use the ```expectedException``` annotation to compatible the different PHPUnit version.
- Let ```testPluralFromValidation``` test method have the ```assertInstanceOf``` assertion and avoid the risky test that don't perform any assertions.

Test enhancement

---

src/Extractors/VueJs.php
tests/assets/vuejs/input.vue

"v-on:.." attribute was skipped previously, but it can contain translations, this fixes it.

VueJS extractor. Include "v-on:" attribute when extracting messages.

---

src/Extractors/VueJs.php

PHP max() fails if it is called on an empty array. This fixes the case if no translations are scanned in a JS file.

VueJs extractor. Fix case when max() fails if array is empty.

---

src/Extractors/Blade.php

Fixed missing custom directives in default Blade compiler instance. We added option to use Facade with all binded parameters for custom blade directives and conditions support.
Issue #197

added option in blade extractor for using blade facade

---

tests/assets/twig/Po.po
tests/assets/twig/Xliff.xlf

This changes the line numbers to let the tests pass again.
Related: https://github.com/oscarotero/Gettext/commit/fe5703caf447320dcaee306c9535016e7f8fac65

Update line numbers for new Twig version

---

src/Extractors/Xliff.php
src/Translation.php
src/Translations.php
tests/AssetsTest.php
tests/assets/xliff/Xliff.xlf

Adds a `Translation::setId` function, with support for the Xliff extractor to call it with the Unit ID.
This permits the library to better conform to xliff's uniqueness requirements (the same source text can be translated several times with different unit IDs) while still supporting PO's uniqueness requirements (the same source text cannot appear twice in the same context).
Note that this means XLIFF files converted to PO files may lose some translations that appear several times with the same source text. (This is necessary to avoid a regression of https://github.com/oscarotero/Gettext/issues/48.)
Note that I did not modify e.g. the PO extractor to use `setId`, even though it supports round-tripping XLIFF unit IDs. These unit IDs can still be read out from the comments or using …

#224 Allow for setting custom ID to avoid translation clobbering

---

src/Extractors/PhpCode.php
src/Translations.php

With this patch:
```
$ vendor/phpunit/phpunit/phpunit 
PHPUnit 5.7.23 by Sebastian Bergmann and contributors.
..........E...................................................... 65 / 99 ( 65%)
..................................                                99 / 99 (100%)
Time: 95 ms, Memory: 8,00MB
There was 1 error:
1) Gettext\Tests\AssetsTest::testTwig
Twig_Error_Syntax: An exception has been thrown during the compilation of a template ("Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)`").
/work/GIT/Gettext/vendor/twig/twig/lib/Twig/Environment.php:566
/work/GIT/Gettext/src/Extractors/Twig.php:30
/work/GIT/Gettext/src/Extractors/Extractor.php:18
/work/GIT/Gettext/src/Translations.php:174 …
```

Fix for PHP 7.4

---

src/Merge.php

The way the `Merge` class is constructed and used makes it difficult and useless to extend. Therefore, it should be marked as `final` to set proper expectations.
Related issue: #231

Mark `Merge` class as `final`

---

src/Extractors/JsCode.php
src/Extractors/Mo.php
src/Extractors/PhpCode.php
src/Extractors/VueJs.php

The FunctionsScanner and StringReader classes are directly referenced in the pieces of logic that use them. If you want to extend one of these, you have to duplicate a big chunk of logic just to change the class reference for the `new` call.
This PR extracts the class name into a protected static property that can be changed in extending classes, to avoid the need to copy-paste big chunks of logic when they need to be changed.
Related issue: #231

Make it easier to extend scanning classes

---

src/Extractors/Po.php
src/Extractors/Xliff.php
src/Translation.php
src/Translations.php

To make the class `Translation` extensible without introducing bugs, the `Translations` class was now adapted to accept a class name of a Translation object to use.
This makes sure that when you extend `Translation`, you can enforce use of that extension even when `Translations` needs to create new instances of it.
`Translation` also has a `create()` method now so that when you have an instance of a translation you can easily create a new one without needing to know the exact class name.
Related issue: #231

Remove direct references to class `Translation`

---

src/Utils/FunctionsScanner.php
tests/AssetsTest.php
tests/assets/phpcode6/input.php

Fixes this error: https://github.com/php-gettext/Gettext/issues/228
There was a wrong `if` condition. Created a test which fails. Patch fixes this simple case.

Fix PHP error when scanning for single domain, but other strings found.

---

src/Extractors/VueJs.php
tests/AssetsTest.php
tests/assets/vuejs3/input.vue

DOMDocument does not handle UTF8 well without using htmlentities() or prepending XM encoding tag.
Added a fix and a test.

Fix UTF-8 handling for VueJs scanner.

---

src/References.php

Hello. I found a bug with GetText. When it updates a translation, if References is a numeric value, the program crashes.
A solution would be checking first if it is a numeric value, else it converts the number into a text string.
ERROR:
`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Gettext\References::add() must be of the type string, int given, called in C:\Users\iinfe\PhpstormProjects\TranslationWorks\vendor\gettext\gettext\src\References.php on line 72 and defined in C:\Users\iinfe\PhpstormProjects\TranslationWorks\vendor\gettext\gettext\src\References.php:31
`
ENTRY EXAMPLE:
```
#. Igor
#: 1
msgctxt "E101_001.PTP:1:3"
msgid ""
"It may be that such a fate awaits you\n"
"in the near future."
msgstr ""
"Puede que tal destino te aguarde en\n"
"un futuro próximo."
```

Fixed integer bug in filename type from references

---

src/Loader/PoLoader.php

If .po file contain multiline disbled translations like this:
#~ msgid "Last agent hours-description"
#~ msgstr ""
#~ "How many hours in the past can system look at finding the last agent? "
#~ "This parameter is only used if 'Call Last Agent' is set to 'YES'."
only the first line was taken, this fix allow mutiline disabled translations.

Multiline disabled translations

---

src/Extractors/Blade.php

In a new Laravel 8 Jetstream project (created with `laravel new [name] --jet`), there is an exception when using `Extractors\Blade::fromFile($file, $translations);`
```
Unable to locate a class or view for component [jet-input].
at vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php:273
269▕         if ($viewFactory->exists($view = $this->guessViewName($component))) {
270▕             return $view;
271▕         }
272▕ 
➜ 273▕         throw new InvalidArgumentException(
274▕             "Unable to locate a class or view for component [{$component}]."
275▕         );
276▕     }
277▕ 
+2 vendor frames 
3   [internal]:0
Illuminate\View\Compilers\ComponentTagCompiler::Illuminate\View\Compilers\{closure}(["<x-jet-input type="password" class="mt-1 block w-3/4" …
```

Blade Extractor improvement for Laravel 8/Jetstream (Gettext 4.x branch)

---

src/Utils/FunctionsScanner.php

It just removes one char for PHP 8 compatibility (at least for [our specs](https://github.com/translation/laravel/tree/master/tests)).
The error fixed is `Argument #1 ($carry) must be passed by reference, value given`
-------
**Note**
We still use the Gettext 4.x branch as dependency in [translation/laravel](https://github.com/translation/laravel) (for [https://translation.io](https://translation.io/laravel)) to be able to keep using the Blade Extractor.
Do you know if someone already made a Blade Scanner compatible with 5.x?
Just for information, how hard do you think it would  be to create this scanner by using the code of your 4.x extractor?
Thanks for this great library!

PHP 8 compatibility (Gettext 4.x branch)

---

src/Comments.php
src/Flags.php
src/Headers.php
src/References.php
src/Translations.php

By setting `#[\ReturnTypeWillChange]` for `JsonSerializable` and `IteratorAggregate` interface implementations the warnings are fixed.
As `#` was previously only a sign for a comment, its backwards compatible to older PHP versions.
Closes #277 (PHP 8.1 compatibility: warnings about JsonSerializable compatibility)

PHP 8.1 compatibility

---

src/Utils/PhpFunctionsScanner.php

Since PHP 8 function calls like `\__( 'Test', 'text-domain' )` are identified as `T_NAME_FULLY_QUALIFIED` instead of `T_STRING`. This will add PHP 8 support for fully qualified function calls like `\__( 'Test', 'text-domain' )`. See following issues for more details:
- https://github.com/php-gettext/Gettext/issues/284
- https://github.com/wp-cli/i18n-command/issues/344

Handle PHP 8 `T_NAME_FULLY_QUALIFIED` to fix issue #284

---

src/Translations.php

Hi, and first thanks a lot for this library!
I've noticed another deprecation warning (ref #280) when upgrading to PHP 8.1 and fixed that here.
```
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated
```

Fixed PHP 8.1 deprecation warning

---

src/Loader/Loader.php
src/Loader/LoaderInterface.php
src/Loader/MoLoader.php
src/Loader/PoLoader.php
src/Loader/StrictPoLoader.php
src/References.php
src/Scanner/ParsedFunction.php
src/Translation.php
src/Translations.php

The upcoming release of PHP 8.4 will deprecate the use of implicit nullable types (`string $str = null`) and requires the explicit nullable type instead (`?string $str = null`). This PR modifies all occurences of the implicit nullable type such that this project should be compatible with PHP 8.4 at least in that regard. The modifications do not change any logic, just adding syntactic sugar, which will be required starting with 8.4.

Fix PHP 8.4 explicit nullable compatibility

---

composer.json
phpstan.dist.neon
src/Comments.php
src/Flags.php
src/Headers.php
src/Loader/MoLoader.php
src/Loader/PoLoader.php
src/Loader/StrictPoLoader.php
src/Merge.php
src/References.php
src/Scanner/FunctionsHandlersTrait.php
src/Scanner/ParsedFunction.php
src/Translation.php
src/Translations.php
tests/BasePoLoaderTestCase.php
tests/MoGeneratorTest.php
tests/PoGeneratorTest.php

Hi @oscarotero, I propose to add PHPStan slowly to improve the type coverage.
It may trigger some architectural questions, for example we are getting this error at level 0:
```
------ ----------------------------------------------------------------------------------- 
Line   src/Flags.php                                                                      
------ ----------------------------------------------------------------------------------- 
21     Unsafe usage of new static().                                                      
🪪  new.static                                                                      
💡 See: https://phpstan.org/blog/solving-phpstan-error-unsafe-usage-of-new-static   
------ ---------------------------------------------------------------------------------- …
```

Add PHPStan level 5

---

.github/workflows/test.yaml
composer.json
rector.php
src/Loader/MoLoader.php
src/Loader/PoLoader.php
src/Loader/StrictPoLoader.php
src/Scanner/FunctionsHandlersTrait.php
src/Scanner/ParsedFunction.php

Add Rector and apply basic rules
